export const ADDRESSES = {
    PEGNET_BURN_ADDRESS: 'EC2BURNFCT2PEGNETooo1oooo1oooo1oooo1oooo1oooo19wthin',
    IS_PRIVATE_KEY: 'IS_PRIVATE_KEY',
    IS_KEY: 'IS_KEY',
    IS_PROBABLY_A_KEY: 'IS_PROBABLY_A_KEY',
    IS_NOT_A_PRIVATE_ADDRESS: 'IS_NOT_A_PRIVATE_ADDRESS',
};

Object.freeze(ADDRESSES);
