export const TRANSACTIONS = {
    TYPE: {
        TRANSFER: 1,
        CONVERSION: 2,
        COINBASE: 3,
        BURN: 4,
    },
    TITLE: {
        INPUTS: 'Inputs',
        OUTPUTS: 'Outputs',
    },
    PEGNET_COMPLETED: 'pegnetCompleted',
    PEGNET_RECORDED: 'pegnetRecorded',
    PEGNET_CHAIN_ID:
        'cffce0f409ebba4ed236d49d89c70e4bd1f1367d86402a3363366683265a242d',
    PEGNET_ASSETS: [
        'EC',
        'PEG',
        'pADA',
        'pBNB',
        'pBRL',
        'pCAD',
        'pCHF',
        'pCNY',
        'pDASH',
        'pDCR',
        'pETH',
        'pEUR',
        'pFCT',
        'pGBP',
        'pHKD',
        'pINR',
        'pJPY',
        'pKRW',
        'pLTC',
        'pMXN',
        'pPHP',
        'pRVN',
        'pSGD',
        'pUSD',
        'pXAG',
        'pXAU',
        'pXBC',
        'pXBT',
        'pXLM',
        'pXMR',
        'pZEC',
    ],

};

Object.freeze(TRANSACTIONS);
